#!/bin/bash

reinstalar () {
apt-get update -y && apt-get upgrade -y && wget https://www.dropbox.com/s/p3n7y9r2srhvjic/inst && bash inst
}

remove () {
echo -e ""
echo -e ""
rm -rf /bin/adm
rm -rf /bin/adm2
rm -rf /bin/adm3
rm -rf /bin/adm4
rm -rf /bin/001
rm -rf /bin/002
rm -rf /bin/badvpn-udpgw
rm -rf /bin/EXTRAIRHOST
rm -rf /bin/speedtest.py
rm -rf /bin/linkextractor
rm -rf /bin/manager
rm -rf /bin/vpnbad
rm -rf /bin/instalacao1
rm -rf /bin/instalacao2
rm -rf /bin/instalacao3
rm -rf /bin/instalacao4
rm -rf /bin/notas
rm -rf /bin/acessos
rm -rf /bin/backup
rm -rf /bin/failban
rm -rf /bin/system
rm -rf /bin/SQUID3IS
rm -rf /bin/teste
rm -rf /bin/user
ssh="/etc/ssh/sshbak"
if [ ! -f "$ssh" ]
then
  echo ""
else
mv -f /etc/ssh/sshbak /etc/ssh/sshd_config
fi
apt-get remove squid3 -y 1>/dev/null 2>/dev/null apt-get remove squid -y 1>/dev/null 2>/dev/null apt-get autoremove -y 1>/dev/null 2>/dev/null
sleep 2s
}

echo -e "\033[1;31mDESINSTALAR OU INSTALAR OUTRO GERENCIADOR?"
echo -e "[1] DESINSTALAR
[2] INSTALAR OUTRO GERENCIADOR\033[0m"
read -p ": " resposta
case $resposta in
 2)
remove
reinstalar
exit
;;
 *)
remove
exit
;;
esac
exit